import * as path from 'path';
import { TargetDef, VSCodeInstall } from './types';

export const TARGETS: TargetDef[] = [
  {
    id: 'cachedData',
    configKey: 'cleanCachedData',
    label: 'Compiled Bytecode (CachedData)',
    detail: 'V8 bytecode cache — auto-regenerated on next launch',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'CachedData')],
  },
  {
    id: 'codeCache',
    configKey: 'cleanCodeCache',
    label: 'Code Cache',
    detail: 'Chromium V8 bytecode cache — auto-regenerated',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'Code Cache')],
  },
  {
    id: 'httpCache',
    configKey: 'cleanHttpCache',
    label: 'HTTP Cache',
    detail: 'Network request cache — like clearing browser cache',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'Cache')],
  },
  {
    id: 'webStorage',
    configKey: 'cleanWebStorage',
    label: 'WebStorage',
    detail: 'Webview asset cache (Service Worker CacheStorage) — auto-regenerated',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'WebStorage')],
  },
  {
    id: 'gpuCaches',
    configKey: 'cleanGPUCaches',
    label: 'GPU Caches',
    detail: 'GPUCache, DawnGraphiteCache, DawnWebGPUCache, VideoDecodeStats — all auto-regenerated',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [
      path.join(i.userDataPath, 'GPUCache'),
      path.join(i.userDataPath, 'DawnGraphiteCache'),
      path.join(i.userDataPath, 'DawnWebGPUCache'),
      path.join(i.userDataPath, 'VideoDecodeStats'),
    ],
  },
  {
    id: 'crashpad',
    configKey: 'cleanCrashpad',
    label: 'Crash Dumps (Crashpad)',
    detail: 'Crash diagnostic files — no app impact',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'Crashpad')],
  },
  {
    id: 'logs',
    configKey: 'cleanLogs',
    label: 'Logs',
    detail: 'VS Code and extension host log files — recreated on next launch',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'logs')],
  },
  {
    id: 'duplicateExtensions',
    configKey: 'cleanDuplicateExtensions',
    label: 'Old Extension Versions',
    detail: 'Old versions of installed extensions — keeps only the newest',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'duplicate-extensions',
    getPaths: (i: VSCodeInstall) => [i.extensionsPath],
  },
  {
    id: 'obsoleteExtensions',
    configKey: 'cleanObsoleteExtensions',
    label: 'Obsolete Extensions (.obsolete)',
    detail: 'Extensions VS Code has already marked for removal — processes the .obsolete file',
    risk: 'safe',
    defaultEnabled: true,
    cleanMode: 'obsolete',
    getPaths: (i: VSCodeInstall) => [i.extensionsPath],
  },
  {
    id: 'cachedExtensionVSIXs',
    configKey: 'cleanCachedExtensionVSIXs',
    label: 'Cached Extension VSIXs',
    detail: 'Downloaded extension packages — VS Code re-downloads if needed',
    risk: 'safe',
    defaultEnabled: false,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'CachedExtensionVSIXs')],
  },
  {
    id: 'networkCache',
    configKey: 'cleanNetworkCache',
    label: 'Network Cache',
    detail: 'Chromium network state cache — minor re-initialization on next launch',
    risk: 'safe',
    defaultEnabled: false,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'Network')],
  },
  {
    id: 'serviceWorkerCache',
    configKey: 'cleanServiceWorkerCache',
    label: 'Service Worker Cache',
    detail: 'Service worker registration cache — extensions re-fetch resources on next webview open',
    risk: 'safe',
    defaultEnabled: false,
    cleanMode: 'directory',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'Service Worker')],
  },
  {
    id: 'orphanedWorkspaceStorage',
    configKey: 'cleanOrphanedWorkspaceStorage',
    label: 'Orphaned Workspace Storage',
    detail: 'Workspace memory (open tabs, scroll positions, extension state) for folders that no longer exist on disk',
    risk: 'permanent',
    warning: 'Permanently deletes saved workspace state — open tabs, scroll positions, extension data — for project folders that no longer exist on disk.',
    defaultEnabled: false,
    cleanMode: 'orphaned-workspace-storage',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'User', 'workspaceStorage')],
  },
  {
    id: 'history',
    configKey: 'cleanHistory',
    label: 'Local History (Timeline)',
    detail: 'File snapshots visible in the Timeline panel — entries older than historyMaxAgeDays days will be deleted',
    risk: 'permanent',
    warning: 'Permanently deletes file history snapshots from the Timeline panel. These cannot be recovered.',
    defaultEnabled: false,
    cleanMode: 'history-age',
    getPaths: (i: VSCodeInstall) => [path.join(i.userDataPath, 'User', 'History')],
  },
];
